/*
 *     Generated by class-dump (version 2.1.5).
 *
 *     class-dump is Copyright (C) 1997, 1999, 2000, 2001 by Steve Nygard.
 */
/*
 * File: /System/Library/Frameworks/AppKit.framework/AppKit
 */

#import <AppKit/AppKit.h>

@interface NSDisclosureButtonCell : NSButtonCell
{
}

- (void)initWithCell:(NSCell *)cell;

@end
