/*
 *     Generated by class-dump (version 2.1.5).
 *
 *     class-dump is Copyright (C) 1997, 1999, 2000, 2001 by Steve Nygard.
 */

/*
 * File: /Volumes/Mac OS X/System/Library/PrivateFrameworks/MachineSettings.framework/Versions/A/MachineSettings
 */

// Note: dumped from Mac OS X 10.1.5; Mac OS X 10.2.1's SoundFileManager is identical.

@class SoundFile;

@interface SoundFileManager
{
    NSMutableArray *_soundFiles;
    NSFileManager *_fileManager;
}

+ (void)initialize;
+ (SoundFileManager *)sharedSoundFileManager;
- (id)init;
- (void)dealloc;
- (void)findSoundFiles;
- (void)addSoundFilesFromDirectory:(NSString *)directory asType:(int)type;
- (void)sortByType;
- (void)sortByName;
- (SoundFile *)soundFileAtIndex:(int)index;
- (int)count;
- (int)indexOfSoundFile:index;
- (SoundFile *)soundFileFromPath:(NSString *)path;
- (SoundFile *)soundFileWithName:(NSString *)name type:(int)type;

@end

@interface SoundFile
{
    int _type;
    NSString *_name;
}

- (id)initWithName:(NSString *)name type:(int)type;
- (void)dealloc;
- (int)type;
- (NSString *)name;
- (NSString *)path;
- (NSString *)pathWithoutExtension;
- (void)setType:(int)type;
- (void)setName:(NSString *)name;
- (int)compareName:(SoundFile *)other;
- (int)compareType:(SoundFile *)other;
- (int)compareNameThenType:(SoundFile *)other;
- (int)compareTypeThenName:(SoundFile *)other;

@end
